module.exports = {
  preset:  process.env.PRESET ||'seo',
  // maxDepth: 10,
  concurrency: process.env.CONCURRENCY || 4,
  // maxRequests: 0,
  followXmlSitemap: process.env.FOLLOW_SITEMAP_XML || false,
  ignoreRobotsTxt: process.env.IGNORE_ROBOTS_TXT || false,
  // headless: true,
  // removeCsv: true,
  // removeJson: true,
  outDir: process.env.OUTPUT_DIR || '~/site-audit-seo/.',
  // gdrive: false,
  // json: false,
  // xlsx: false,
  // upload: false,
  lang: 'en',
  // openFile: true,
  // docsExtensions: ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'pdf', 'rar', 'zip']
  readingTime: process.env.READING_TIME_ENABLED || false,
    // enabled: process.env.READING_TIME_ENABLED || false,
  htmlGrabbr: {
    // active: process.env.HTMLGRABBER_ENABLED || true,
    debug: false,
    pretty: false,
    pageIllustration: true,
    excerpt: true,
    readLength: true,
    embeddedImageURLs: true,    
  },
  influxdb: {
    // active: process.env.INFLUXDB_ENABLED || false,
    host: process.env.INFLUXDB_HOST || 'influxdb',
    port: process.env.INFLUXDB_PORT || 8086,
    database: process.env.INFLUXDB_DATABASE || 'site-audit-seo',
    measurement: process.env.INFLUXDB_MEASUREMENT || 'site_audit_seo', // optional
    username: process.env.INFLUXDB_USER || 'default',
    password: process.env.INFLUXDB_USER_PASSWORD || '',
    maxSendCount: process.env.INFLUXDB_MAX_SEND_COUNT || 5, // optional, default send part of pages
  },
  yake: {
    // active: process.env.YAKE_ENABLED || false,
    serverUrl: process.env.YAKE_SERVER_URL || 'http://localhost:5000/yake/',
    language: process.env.YAKE_DEFAULT_LANGUAGE || 'en',
    maxNgramSize: process.env.YAKE_MAX_NGRAM_SIZE || 3,    
    numberKeywords: process.env.YAKE_NUMBER_KEYWORDS || 10,
  },
};
