FROM mhart/alpine-node:12

RUN apk update && \ 
    apk upgrade && \
    apk add --no-cache git nano bash jq git ca-certificates && \
    git clone --depth=1 --recursive https://github.com/viasite/site-audit-seo-viewer /app

WORKDIR /app
RUN npm install

# Only copy over the node pieces we need from the above image
FROM  mhart/alpine-node:12

WORKDIR /app
COPY --from=0 /app .

EXPOSE 3001
CMD ["cross-env", "HOST=0.0.0.0", "PORT=3001", "nuxt"]
